style:
  include:
    - com/earuile/bubble/ui/controllers/color.css
    - com/earuile/bubble/ui/controllers/start/start.css
    - com/earuile/bubble/ui/controllers/registration/registration.css
    - com/earuile/bubble/ui/controllers/chat/chat.css
    - com/earuile/bubble/ui/controllers/chatcell/chatcell.css
    - com/earuile/bubble/ui/controllers/dialogs/dialogs.css
    - com/earuile/bubble/ui/controllers/message/message-style.css
